# Generated by Django 5.2.11 on 2026-02-19 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_invoice_viewed', models.BooleanField(default=True)),
                ('email_payment_received', models.BooleanField(default=True)),
                ('in_app_invoice_created', models.BooleanField(default=True)),
                ('in_app_invoice_viewed', models.BooleanField(default=True)),
                ('in_app_payment_received', models.BooleanField(default=True)),
                ('in_app_client_created', models.BooleanField(default=True)),
                ('in_app_expense_created', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
