# Generated by Django 5.2.11 on 2026-02-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='email_low_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_low_stock',
            field=models.BooleanField(default=True),
        ),
    ]
