# Generated by Django 5.2.11 on 2026-02-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationsetting_email_low_stock_and_more'),
        ('users', '0011_teammemberinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.business'),
        ),
    ]
