# Generated by Django 5.2.11 on 2026-02-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='email_overdue_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_overdue_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_target_reached',
            field=models.BooleanField(default=True),
        ),
    ]
