# Generated by Django 5.2.11 on 2026-02-23 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationsetting_email_overdue_invoice_and_more'),
        ('users', '0012_teammember_monthly_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Yaradıldı'), ('UPDATE', 'Yeniləndi'), ('DELETE', 'Silindi'), ('LOGIN', 'Giriş'), ('EXPORT', 'Eksport'), ('OTHER', 'Digər')], default='OTHER', max_length=20)),
                ('module', models.CharField(choices=[('INVOICE', 'Faktura'), ('PAYMENT', 'Ödəniş'), ('CLIENT', 'Müştəri'), ('PRODUCT', 'Məhsul'), ('EXPENSE', 'Xərc'), ('TEAM', 'Komanda'), ('SETTINGS', 'Tənzimləmələr'), ('AUTH', 'Sistem')], default='AUTH', max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='users.business')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
