# Generated by Django 5.2.11 on 2026-03-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_product_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_warehouse_created',
            field=models.BooleanField(default=True),
        ),
    ]
