# Generated by Django 5.2.11 on 2026-03-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notificationsetting_in_app_product_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_purchase_order_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_purchase_order_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(choices=[('INVOICE', 'Faktura'), ('PAYMENT', 'Ödəniş'), ('CLIENT', 'Müştəri'), ('PRODUCT', 'Məhsul'), ('PURCHASE_ORDER', 'Alış Sifarişi'), ('EXPENSE', 'Xərc'), ('TEAM', 'Komanda'), ('SETTINGS', 'Tənzimləmələr'), ('AUTH', 'Sistem')], default='AUTH', max_length=20),
        ),
    ]
