# Generated by Django 5.2.11 on 2026-02-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_business_budget_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, help_text='SKU və ya Barcode', max_length=100, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'Ədəd'), ('kg', 'Kq'), ('m', 'Metr'), ('l', 'Litr'), ('service', 'Xidmət')], default='pcs', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.business')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'sku')},
            },
        ),
    ]
