# Generated by Django 5.2.11 on 2026-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bildiriş üçün minimum miqdar', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
