# Generated by Django 5.2.11 on 2026-03-04 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_deleted_at_product_is_deleted'),
        ('users', '0016_business_default_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Mayalıq / alış qiyməti', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Satış qiyməti', max_digits=12),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_name', models.CharField(help_text='Təchizatçı adı', max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('order_number', models.CharField(blank=True, help_text='Sifariş nömrəsi', max_length=50, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Qaralama'), ('ORDERED', 'Sifariş verildi'), ('RECEIVED', 'Qəbul edildi'), ('PARTIAL', 'Qismən qəbul'), ('CANCELLED', 'Ləğv edildi')], default='DRAFT', max_length=20)),
                ('order_date', models.DateField(help_text='Sifariş tarixi')),
                ('expected_date', models.DateField(blank=True, help_text='Gözlənilən gəliş tarixi', null=True)),
                ('received_date', models.DateField(blank=True, help_text='Faktiki qəbul tarixi', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='users.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, help_text='Sifariş edilən miqdar', max_digits=12)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0.0, help_text='Qəbul edilən miqdar', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Vahid alış qiyməti', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='inventory.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Anbar adı (məs: Əsas Anbar, Dükan #2)', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Əsas anbar kimi istifadə olunsun?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='users.business')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Giriş (Alış)'), ('OUT', 'Çıxış (Satış)'), ('ADJUSTMENT_PLUS', 'Düzəliş (+)'), ('ADJUSTMENT_MINUS', 'Düzəliş (-)'), ('TRANSFER', 'Anbarlar arası köçürmə'), ('RETURN', 'Geri qaytarma'), ('WRITE_OFF', 'Silinmə (Xarab/İtkili)')], max_length=20)),
                ('source_type', models.CharField(choices=[('INVOICE', 'Faktura'), ('PURCHASE', 'Alış Sifarişi'), ('ADJUSTMENT', 'İnventarizasiya'), ('MANUAL', 'Əl ilə dəyişiklik'), ('TRANSFER', 'Köçürmə')], default='MANUAL', max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='Mənbə sənədin ID-si (Faktura, Alış sifarişi və s.)', null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Hərəkət miqdarı (həmişə müsbət)', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Vahid maya dəyəri', max_digits=12)),
                ('stock_before', models.DecimalField(decimal_places=2, help_text='Hərəkətdən əvvəlki stok', max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=2, help_text='Hərəkətdən sonrakı stok', max_digits=12)),
                ('note', models.TextField(blank=True, help_text='Qeyd / Şərh', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='users.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.DecimalField(decimal_places=2, help_text='Sistemdəki qalıq', max_digits=12)),
                ('new_quantity', models.DecimalField(decimal_places=2, help_text='Real sayılmış qalıq', max_digits=12)),
                ('reason', models.CharField(choices=[('COUNT', 'Fiziki sayım'), ('DAMAGE', 'Xarab olma'), ('LOSS', 'İtki / Oğurluq'), ('FOUND', 'Tapıntı'), ('EXPIRY', 'Yararlılıq müddəti bitib'), ('OTHER', 'Digər')], default='COUNT', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='users.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Məhsulun saxlandığı anbar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.warehouse'),
        ),
    ]
