# Generated by Django 5.2.11 on 2026-03-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchaseorderreceipt_purchaseorderreceiptitem'),
        ('users', '0022_add_tax_regime_support'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'sku', 'warehouse')},
        ),
    ]
