# Generated by Django 5.2.11 on 2026-02-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_deleted_at_client_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('foreign', 'Foreign / Non-resident')], default='company', max_length=20),
        ),
    ]
