import React, { useState } from 'react';
import { useBusiness } from '../context/BusinessContext';
import { useQuery } from '@tanstack/react-query';
import clientApi from '../api/client';
import {
    Coins,
    BarChart3,
    TrendingUp,
    TrendingDown,
    Calendar,
    Printer,
    Download,
    Calculator,
    PieChart,
    ChevronDown,
    FileText,
    Percent
} from 'lucide-react';
import {
    BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
    PieChart as RePieChart, Pie, Cell, LineChart, Line, AreaChart, Area
} from 'recharts';

const TaxReports = () => {
    const { activeBusiness } = useBusiness();
    const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
    const [taxMode, setTaxMode] = useState('simplified'); // 'simplified' or 'profit'

    const { data: taxData, isLoading } = useQuery({
        queryKey: ['tax-analytics', activeBusiness?.id, selectedYear],
        queryFn: async () => {
            const res = await clientApi.get(`/invoices/analytics/tax/?year=${selectedYear}`);
            return res.data;
        },
        enabled: !!activeBusiness
    });

    if (isLoading) return <div className="p-12 text-center" style={{ color: 'var(--color-text-muted)' }}>Yüklənir...</div>;
    if (!taxData) return <div className="p-12 text-center" style={{ color: 'var(--color-text-muted)' }}>Məlumat tapılmadı.</div>;

    const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];

    const handlePrint = () => window.print();

    return (
        <div className="space-y-8 pb-12 print:p-0">
            {/* Header - Hidden in Print */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 print:hidden">
                <div>
                    <h2 className="text-3xl font-black text-[var(--color-text-primary)] tracking-tight font-roboto uppercase">Vergi və Hesabatlar</h2>
                    <p className="text-[var(--color-text-secondary)] mt-1">Vergi öhdəliklərinizi və maliyyə hesabatlarınızı buradan izləyin.</p>
                </div>
                <div className="flex items-center gap-3">
                    <select
                        value={selectedYear}
                        onChange={(e) => setSelectedYear(Number(e.target.value))}
                        className="bg-[var(--color-card-bg)] border border-[var(--color-card-border)] rounded-xl px-4 py-2 font-bold text-[var(--color-text-primary)] shadow-sm outline-none focus:ring-2 focus:ring-primary-blue transition-all"
                    >
                        {[2024, 2025, 2026].map(y => <option key={y} value={y}>{y}</option>)}
                    </select>
                    <button
                        onClick={handlePrint}
                        className="flex items-center gap-2 px-5 py-2 rounded-xl font-bold transition-all shadow-md active:scale-95"
                        style={{ backgroundColor: 'var(--color-brand-dark)', color: 'white' }}
                    >
                        <Printer size={18} />
                        <span>Çap et</span>
                    </button>
                </div>
            </div>

            {/* Print Header - Visible only in Print */}
            <div className="hidden print:block border-b-2 border-slate-900 pb-8 mb-8">
                <div className="flex justify-between items-end">
                    <div>
                        <h1 className="text-4xl font-black">{activeBusiness?.name}</h1>
                        <p className="text-xl font-bold text-slate-600">İllik Vergi Hesabatı - {selectedYear}</p>
                        <p className="text-sm mt-2">VÖEN: {activeBusiness?.voen}</p>
                    </div>
                    <div className="text-right">
                        <p className="text-sm">Tarix: {(() => {
                            const d = new Date();
                            const m = ['Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'İyun', 'İyul', 'Avqust', 'Sentyabr', 'Oktyabr', 'Noyabr', 'Dekabr'];
                            return `${d.getDate()} ${m[d.getMonth()]} ${d.getFullYear()}`;
                        })()}</p>
                        <p className="text-sm italic">Generated by InvoiceAZ</p>
                    </div>
                </div>
            </div>

            {/* 1. KPI SECTION */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                <div className="p-6 rounded-3xl border shadow-sm hover:shadow-md transition-all group overflow-hidden relative" style={{ backgroundColor: 'var(--color-card-bg)', borderColor: 'var(--color-card-border)' }}>
                    <div className="absolute top-0 right-0 w-24 h-24 bg-blue-500/5 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110" />
                    <div className="flex flex-col relative">
                        <div className="p-3 rounded-2xl w-fit mb-4" style={{ backgroundColor: 'var(--color-brand-light)', color: 'var(--color-brand)' }}>
                            <TrendingUp size={24} />
                        </div>
                        <span className="text-xs font-bold uppercase tracking-widest" style={{ color: 'var(--color-text-muted)' }}>Ümumi Gəlir</span>
                        <div className="flex items-baseline gap-2 mt-1">
                            <span className="text-2xl font-black" style={{ color: 'var(--color-text-primary)' }}>{taxData.income_tax.revenue.toLocaleString()}</span>
                            <span className="text-sm font-bold opacity-50" style={{ color: 'var(--color-text-secondary)' }}>AZN</span>
                        </div>
                    </div>
                </div>

                <div className="p-6 rounded-3xl border shadow-sm hover:shadow-md transition-all group overflow-hidden relative" style={{ backgroundColor: 'var(--color-card-bg)', borderColor: 'var(--color-card-border)' }}>
                    <div className="absolute top-0 right-0 w-24 h-24 bg-red-500/5 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110" />
                    <div className="flex flex-col relative">
                        <div className="p-3 rounded-2xl w-fit mb-4" style={{ backgroundColor: '#EF444415', color: '#EF4444' }}>
                            <TrendingDown size={24} />
                        </div>
                        <span className="text-xs font-bold uppercase tracking-widest" style={{ color: 'var(--color-text-muted)' }}>Ümumi Xərclər</span>
                        <div className="flex items-baseline gap-2 mt-1">
                            <span className="text-2xl font-black" style={{ color: 'var(--color-text-primary)' }}>{taxData.income_tax.expenses.toLocaleString()}</span>
                            <span className="text-sm font-bold opacity-50" style={{ color: 'var(--color-text-secondary)' }}>AZN</span>
                        </div>
                    </div>
                </div>

                <div className="p-6 rounded-3xl border shadow-sm hover:shadow-md transition-all group overflow-hidden relative" style={{ backgroundColor: 'var(--color-card-bg)', borderColor: 'var(--color-card-border)' }}>
                    <div className="absolute top-0 right-0 w-24 h-24 bg-green-500/5 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110" />
                    <div className="flex flex-col relative">
                        <div className="p-3 rounded-2xl w-fit mb-4" style={{ backgroundColor: '#10B98115', color: '#10B981' }}>
                            <Calculator size={24} />
                        </div>
                        <span className="text-xs font-bold uppercase tracking-widest" style={{ color: 'var(--color-text-muted)' }}>Vergi Bazası</span>
                        <div className="flex items-baseline gap-2 mt-1">
                            <span className="text-2xl font-black" style={{ color: 'var(--color-text-primary)' }}>{taxData.income_tax.tax_base.toLocaleString()}</span>
                            <span className="text-sm font-bold opacity-50" style={{ color: 'var(--color-text-secondary)' }}>AZN</span>
                        </div>
                    </div>
                </div>

                <div className="p-6 rounded-3xl border shadow-sm hover:shadow-md transition-all group overflow-hidden relative" style={{ backgroundColor: 'var(--color-card-bg)', borderColor: 'var(--color-card-border)' }}>
                    <div className="absolute top-0 right-0 w-24 h-24 bg-amber-500/5 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110" />
                    <div className="flex flex-col relative">
                        <div className="p-3 rounded-2xl w-fit mb-4" style={{ backgroundColor: '#F59E0B15', color: '#F59E0B' }}>
                            <Coins size={24} />
                        </div>
                        <span className="text-xs font-bold uppercase tracking-widest" style={{ color: 'var(--color-text-muted)' }}>Toplanmış ƏDV</span>
                        <div className="flex items-baseline gap-2 mt-1">
                            <span className="text-2xl font-black" style={{ color: 'var(--color-text-primary)' }}>{taxData.vat.total.toLocaleString()}</span>
                            <span className="text-sm font-bold opacity-50" style={{ color: 'var(--color-text-secondary)' }}>AZN</span>
                        </div>
                    </div>
                </div>
            </div>

            {/* 2. VAT SECTION */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                <div className="lg:col-span-8 bg-[var(--color-card-bg)] p-8 rounded-3xl border border-[var(--color-card-border)] shadow-sm space-y-6">
                    <div className="flex justify-between items-center">
                        <h3 className="text-xl font-bold flex items-center gap-2 text-[var(--color-text-primary)]"><PieChart className="text-primary-blue" /> Aylıq ƏDV Dinamikası</h3>
                        <div className="bg-blue-500/10 text-blue-500 px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider">Hesablanmış</div>
                    </div>
                    <div className="h-[300px] w-full">
                        <ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={0} debounce={200}>
                            <AreaChart data={taxData.vat.monthly}>
                                <defs>
                                    <linearGradient id="colorVat" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.1} />
                                        <stop offset="95%" stopColor="#3b82f6" stopOpacity={0} />
                                    </linearGradient>
                                </defs>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--color-card-border)" />
                                <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'var(--color-text-muted)' }} dy={10} />
                                <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'var(--color-text-muted)' }} />
                                <Tooltip
                                    contentStyle={{ backgroundColor: 'var(--color-card-bg)', borderRadius: '16px', border: '1px solid var(--color-card-border)', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                                    formatter={(val) => [`${val.toLocaleString()} AZN`, 'ƏDV']}
                                />
                                <Area type="monotone" dataKey="vat" stroke="#3b82f6" strokeWidth={3} fillOpacity={1} fill="url(#colorVat)" />
                            </AreaChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                <div
                    className="lg:col-span-4 p-8 rounded-3xl shadow-xl space-y-8 relative overflow-hidden border"
                    style={{ backgroundColor: 'var(--color-card-bg)', borderColor: 'var(--color-card-border)', color: 'var(--color-text-primary)' }}
                >
                    <div className="absolute bottom-0 right-0 w-48 h-48 bg-blue-500/5 rounded-tl-full -mr-12 -mb-12 pointer-events-none" />
                    <div>
                        <h3 className="text-xl font-bold" style={{ color: 'var(--color-text-primary)' }}>ƏDV Bölgüsü</h3>
                        <p className="text-sm mt-1" style={{ color: 'var(--color-text-secondary)' }}>Rate üzrə vergi daxilolmaları</p>
                    </div>

                    <div className="space-y-6">
                        <div className="flex justify-between items-end border-b pb-4" style={{ borderColor: 'var(--color-card-border)' }}>
                            <div>
                                <span className="text-[10px] font-black uppercase tracking-widest" style={{ color: 'var(--color-text-muted)' }}>18% Rate</span>
                                <p className="text-2xl font-black mt-1" style={{ color: 'var(--color-text-primary)' }}>
                                    {taxData.vat.by_rate.rate_18.toLocaleString()} <span className="text-sm font-bold opacity-50">AZN</span>
                                </p>
                            </div>
                            <div className="w-12 h-12 rounded-xl bg-blue-500/10 flex items-center justify-center text-blue-500">
                                <Percent size={20} />
                            </div>
                        </div>

                        <div className="flex justify-between items-end border-b pb-4" style={{ borderColor: 'var(--color-card-border)' }}>
                            <div>
                                <span className="text-[10px] font-black uppercase tracking-widest" style={{ color: 'var(--color-text-muted)' }}>0% Rate (Azad)</span>
                                <p className="text-2xl font-black mt-1" style={{ color: 'var(--color-text-primary)' }}>
                                    {taxData.vat.by_rate.rate_0.toLocaleString()} <span className="text-sm font-bold opacity-50">AZN</span>
                                </p>
                            </div>
                            <div className="w-12 h-12 rounded-xl flex items-center justify-center" style={{ backgroundColor: 'var(--color-badge-bg)', color: 'var(--color-text-muted)' }}>
                                <Percent size={20} />
                            </div>
                        </div>

                        <div className="pt-4">
                            <div className="flex justify-between items-center mb-2">
                                <span className="text-sm font-bold" style={{ color: 'var(--color-text-secondary)' }}>Yekun Ödənilməli ƏDV</span>
                                <span className="text-xl font-bold text-blue-500">{taxData.vat.total.toLocaleString()} AZN</span>
                            </div>
                            <div className="w-full h-2 rounded-full overflow-hidden" style={{ backgroundColor: 'var(--color-badge-bg)' }}>
                                <div className="bg-blue-500 h-full w-[100%]" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* 3. QUARTERLY & INCOME TAX */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Quarterly table */}
                <div className="bg-[var(--color-card-bg)] p-8 rounded-3xl border border-[var(--color-card-border)] shadow-sm space-y-6">
                    <div>
                        <h3 className="text-xl font-bold font-roboto text-[var(--color-text-primary)]">Rüblük Hesabatlar</h3>
                        <p className="text-sm text-[var(--color-text-secondary)]">Hər rüb üzrə maliyyə və vergi xülasəsi</p>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full text-left border-collapse">
                            <thead>
                                <tr className="text-xs text-[var(--color-text-muted)] uppercase tracking-widest border-b border-[var(--color-card-border)]">
                                    <th className="pb-4 pt-2">Rüb</th>
                                    <th className="pb-4 pt-2">Gəlir</th>
                                    <th className="pb-4 pt-2">Xərc</th>
                                    <th className="pb-4 pt-2">ƏDV</th>
                                    <th className="pb-4 pt-2 text-right">Mənfəət</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-[var(--color-card-border)]">
                                {taxData.quarterly.map((q, idx) => (
                                    <tr key={idx} className="group hover:bg-[var(--color-hover-bg)] transition-colors">
                                        <td className="py-4 font-black text-[var(--color-text-primary)]">{q.name}</td>
                                        <td className="py-4 font-bold text-[var(--color-text-secondary)]">{q.revenue.toLocaleString()}</td>
                                        <td className="py-4 text-[var(--color-text-muted)]">{q.expenses.toLocaleString()}</td>
                                        <td className="py-4 text-[var(--color-text-muted)]">{q.vat.toLocaleString()}</td>
                                        <td className={`py-4 font-black text-right ${q.profit >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                                            {q.profit.toLocaleString()}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>

                {/* Tax Estimates */}
                <div className="bg-[var(--color-card-bg)] p-8 rounded-3xl border border-[var(--color-card-border)] shadow-sm space-y-6">
                    <div className="flex justify-between items-center">
                        <div>
                            <h3 className="text-xl font-bold font-roboto text-[var(--color-text-primary)]">Təxmini Vergilər</h3>
                            <p className="text-sm text-[var(--color-text-secondary)]">Müxtəlif vergi modelləri üzrə proqnozlar</p>
                        </div>
                        <div className="flex bg-[var(--color-hover-bg)] p-1 rounded-xl">
                            <button
                                onClick={() => setTaxMode('simplified')}
                                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${taxMode === 'simplified' ? 'bg-[var(--color-card-bg)] text-[var(--color-text-primary)] shadow-sm' : 'text-[var(--color-text-muted)]'}`}
                            >
                                Sadə
                            </button>
                            <button
                                onClick={() => setTaxMode('profit')}
                                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${taxMode === 'profit' ? 'bg-[var(--color-card-bg)] text-[var(--color-text-primary)] shadow-sm' : 'text-[var(--color-text-muted)]'}`}
                            >
                                Mənfəət
                            </button>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 gap-4">
                        {taxMode === 'simplified' ? (
                            <div className="border p-6 rounded-2xl space-y-4" style={{ backgroundColor: 'var(--color-brand-light)', borderColor: 'var(--color-brand-shadow)' }}>
                                <div className="flex justify-between items-center">
                                    <span className="text-sm font-bold" style={{ color: 'var(--color-brand-dark)' }}>Sadələşdirilmiş Vergi (2%)</span>
                                    <span className="text-2xl font-black" style={{ color: 'var(--color-brand)' }}>{taxData.income_tax.estimates.simplified_2pct.toLocaleString()} AZN</span>
                                </div>
                                <p className="text-xs opacity-70" style={{ color: 'var(--color-brand)' }}>Ümumi dövriyyə (Gəlir) əsasında hesablanır.</p>
                            </div>
                        ) : (
                            <div className="space-y-4">
                                <div className="p-6 rounded-2xl space-y-4" style={{ backgroundColor: 'var(--color-badge-bg)', border: '1px solid var(--color-card-border)' }}>
                                    <div className="flex justify-between items-center">
                                        <span className="text-sm font-bold" style={{ color: 'var(--color-text-primary)' }}>Mənfəət Vergisi (20%)</span>
                                        <span className="text-2xl font-black" style={{ color: 'var(--color-brand)' }}>{taxData.income_tax.estimates.profit_20pct.toLocaleString()} AZN</span>
                                    </div>
                                    <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>Gəlir ilə xərc fərqi əsasında standart dərəcə ilə hesablanır.</p>
                                </div>
                                <div className="p-6 rounded-2xl space-y-4" style={{ backgroundColor: 'var(--color-hover-bg)', border: '1px solid var(--color-card-border)' }}>
                                    <div className="flex justify-between items-center">
                                        <span className="text-sm font-bold" style={{ color: 'var(--color-text-primary)' }}>Mikro Sahibkar (5%)</span>
                                        <span className="text-2xl font-black text-emerald-500">{taxData.income_tax.estimates.micro_5pct.toLocaleString()} AZN</span>
                                    </div>
                                    <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>Gəlir və xərc fərqi əsasında 75% güzəştli dərəcə ilə.</p>
                                </div>
                            </div>
                        )}
                    </div>

                    <div className="pt-2">
                        <div className="bg-[var(--color-hover-bg)] rounded-2xl p-4 flex items-start gap-3">
                            <div className="p-2 bg-[var(--color-card-bg)] rounded-lg border border-[var(--color-card-border)] text-[var(--color-text-muted)]">
                                <FileText size={16} />
                            </div>
                            <p className="text-[10px] text-[var(--color-text-muted)] leading-relaxed italic">
                                * Bu rəqəmlər yalnız məlumatlandırma məqsədi daşıyır və tətbiqdə olan dataya əsaslanır.
                                Rəsmi bəyannamələr üçün peşəkar mühasibat xidmətindən istifadə etməyiniz tövsiyə olunur.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Print Only Summary Table */}
            <div className="hidden print:block mt-12">
                <h3 className="text-xl font-bold mb-6">İl Sonu Maliyyə Xülasəsi</h3>
                <div className="grid grid-cols-2 gap-12">
                    <div className="space-y-4">
                        <div className="flex justify-between border-b py-2"><span>Yekun Gəlir:</span><span className="font-bold">{taxData.income_tax.revenue.toLocaleString()} AZN</span></div>
                        <div className="flex justify-between border-b py-2"><span>Yekun Xərc:</span><span className="font-bold">{taxData.income_tax.expenses.toLocaleString()} AZN</span></div>
                        <div className="flex justify-between border-b py-2 text-xl font-black pt-4"><span>Xalis Mənfəət:</span><span>{taxData.income_tax.tax_base.toLocaleString()} AZN</span></div>
                    </div>
                    <div className="space-y-4">
                        <div className="flex justify-between border-b py-2"><span>Hesablanmış ƏDV (Yekun):</span><span className="font-bold">{taxData.vat.total.toLocaleString()} AZN</span></div>
                        <div className="flex justify-between border-b py-2"><span>Müştəri Sayı:</span><span className="font-bold">{taxData.summary.customer_count}</span></div>
                        <div className="flex justify-between border-b py-2"><span>Ən Uğurlu Ay:</span><span className="font-bold">{taxData.summary.best_month}</span></div>
                    </div>
                </div>
                <div className="mt-20 border-t pt-8 text-center text-xs text-slate-400">
                    Sənəd InvoiceAZ platforması tərəfindən {new Date().toLocaleString('az-AZ')} tarixində generasiya edilmişdir.
                </div>
            </div>
        </div>
    );
};

export default TaxReports;
