import React, { useState } from 'react';
import { useBusiness } from '../context/BusinessContext';
import { useQuery } from '@tanstack/react-query';
import clientApi from '../api/client';
import {
    Coins,
    BarChart3,
    TrendingUp,
    TrendingDown,
    Calendar,
    Printer,
    Download,
    Calculator,
    PieChart,
    ChevronDown,
    FileText,
    Percent
} from 'lucide-react';
import {
    BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
    PieChart as RePieChart, Pie, Cell, LineChart, Line, AreaChart, Area
} from 'recharts';

const TaxReports = () => {
    const { activeBusiness } = useBusiness();
    const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
    const [taxMode, setTaxMode] = useState('simplified'); // 'simplified' or 'profit'

    const { data: taxData, isLoading } = useQuery({
        queryKey: ['tax-analytics', activeBusiness?.id, selectedYear],
        queryFn: async () => {
            const res = await clientApi.get(`/invoices/analytics/tax/?year=${selectedYear}`);
            return res.data;
        },
        enabled: !!activeBusiness
    });

    if (isLoading) return <div className="p-12 text-center text-gray-400">Yüklənir...</div>;
    if (!taxData) return <div className="p-12 text-center text-gray-400">Məlumat tapılmadı.</div>;

    const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];

    const handlePrint = () => window.print();

    return (
        <div className="space-y-8 pb-12 print:p-0">
            {/* Header - Hidden in Print */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 print:hidden">
                <div>
                    <h2 className="text-3xl font-black text-slate-900 tracking-tight font-outfit uppercase">Vergi və Hesabatlar</h2>
                    <p className="text-slate-500 mt-1">Vergi öhdəliklərinizi və maliyyə hesabatlarınızı buradan izləyin.</p>
                </div>
                <div className="flex items-center gap-3">
                    <select
                        value={selectedYear}
                        onChange={(e) => setSelectedYear(Number(e.target.value))}
                        className="bg-white border rounded-xl px-4 py-2 font-bold text-slate-700 shadow-sm outline-none focus:ring-2 focus:ring-primary-blue transition-all"
                    >
                        {[2024, 2025, 2026].map(y => <option key={y} value={y}>{y}</option>)}
                    </select>
                    <button
                        onClick={handlePrint}
                        className="flex items-center gap-2 bg-slate-800 text-white px-5 py-2 rounded-xl font-bold hover:bg-slate-700 transition-all shadow-md active:scale-95"
                    >
                        <Printer size={18} />
                        <span>Çap et</span>
                    </button>
                </div>
            </div>

            {/* Print Header - Visible only in Print */}
            <div className="hidden print:block border-b-2 border-slate-900 pb-8 mb-8">
                <div className="flex justify-between items-end">
                    <div>
                        <h1 className="text-4xl font-black">{activeBusiness?.name}</h1>
                        <p className="text-xl font-bold text-slate-600">İllik Vergi Hesabatı - {selectedYear}</p>
                        <p className="text-sm mt-2">VÖEN: {activeBusiness?.voen}</p>
                    </div>
                    <div className="text-right">
                        <p className="text-sm">Tarix: {new Date().toLocaleDateString('az-AZ')}</p>
                        <p className="text-sm italic">Generated by InvoiceAZ</p>
                    </div>
                </div>
            </div>

            {/* 1. KPI SECTION */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                <div className="bg-white p-6 rounded-3xl border shadow-sm hover:shadow-md transition-all group overflow-hidden relative">
                    <div className="absolute top-0 right-0 w-24 h-24 bg-blue-50 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110" />
                    <div className="flex flex-col relative">
                        <div className="p-3 bg-blue-100 text-blue-600 rounded-2xl w-fit mb-4">
                            <TrendingUp size={24} />
                        </div>
                        <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Ümumi Gəlir</span>
                        <div className="flex items-baseline gap-2 mt-1">
                            <span className="text-2xl font-black text-slate-900">{taxData.income_tax.revenue.toLocaleString()}</span>
                            <span className="text-sm font-bold text-slate-500">AZN</span>
                        </div>
                    </div>
                </div>

                <div className="bg-white p-6 rounded-3xl border shadow-sm hover:shadow-md transition-all group overflow-hidden relative">
                    <div className="absolute top-0 right-0 w-24 h-24 bg-red-50 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110" />
                    <div className="flex flex-col relative">
                        <div className="p-3 bg-red-100 text-red-600 rounded-2xl w-fit mb-4">
                            <TrendingDown size={24} />
                        </div>
                        <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Ümumi Xərclər</span>
                        <div className="flex items-baseline gap-2 mt-1">
                            <span className="text-2xl font-black text-slate-900">{taxData.income_tax.expenses.toLocaleString()}</span>
                            <span className="text-sm font-bold text-slate-500">AZN</span>
                        </div>
                    </div>
                </div>

                <div className="bg-white p-6 rounded-3xl border shadow-sm hover:shadow-md transition-all group overflow-hidden relative">
                    <div className="absolute top-0 right-0 w-24 h-24 bg-green-50 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110" />
                    <div className="flex flex-col relative">
                        <div className="p-3 bg-green-100 text-green-600 rounded-2xl w-fit mb-4">
                            <Calculator size={24} />
                        </div>
                        <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Vergi Bazası</span>
                        <div className="flex items-baseline gap-2 mt-1">
                            <span className="text-2xl font-black text-slate-900">{taxData.income_tax.tax_base.toLocaleString()}</span>
                            <span className="text-sm font-bold text-slate-500">AZN</span>
                        </div>
                    </div>
                </div>

                <div className="bg-white p-6 rounded-3xl border shadow-sm hover:shadow-md transition-all group overflow-hidden relative">
                    <div className="absolute top-0 right-0 w-24 h-24 bg-amber-50 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110" />
                    <div className="flex flex-col relative">
                        <div className="p-3 bg-amber-100 text-amber-600 rounded-2xl w-fit mb-4">
                            <Coins size={24} />
                        </div>
                        <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Toplanmış ƏDV</span>
                        <div className="flex items-baseline gap-2 mt-1">
                            <span className="text-2xl font-black text-slate-900">{taxData.vat.total.toLocaleString()}</span>
                            <span className="text-sm font-bold text-slate-500">AZN</span>
                        </div>
                    </div>
                </div>
            </div>

            {/* 2. VAT SECTION */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                <div className="lg:col-span-8 bg-white p-8 rounded-3xl border shadow-sm space-y-6">
                    <div className="flex justify-between items-center">
                        <h3 className="text-xl font-bold flex items-center gap-2"><PieChart className="text-primary-blue" /> Aylıq ƏDV Dinamikası</h3>
                        <div className="bg-blue-50 text-blue-700 px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider">Hesablanmış</div>
                    </div>
                    <div className="h-[300px] w-full">
                        <ResponsiveContainer width="100%" height="100%">
                            <AreaChart data={taxData.vat.monthly}>
                                <defs>
                                    <linearGradient id="colorVat" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.1} />
                                        <stop offset="95%" stopColor="#3b82f6" stopOpacity={0} />
                                    </linearGradient>
                                </defs>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                                <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#94a3b8' }} dy={10} />
                                <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#94a3b8' }} />
                                <Tooltip
                                    contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                                    formatter={(val) => [`${val.toLocaleString()} AZN`, 'ƏDV']}
                                />
                                <Area type="monotone" dataKey="vat" stroke="#3b82f6" strokeWidth={3} fillOpacity={1} fill="url(#colorVat)" />
                            </AreaChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                <div className="lg:col-span-4 bg-slate-900 text-white p-8 rounded-3xl shadow-xl space-y-8 relative overflow-hidden">
                    <div className="absolute bottom-0 right-0 w-48 h-48 bg-blue-500/10 rounded-tl-full -mr-12 -mb-12 pointer-events-none" />
                    <div>
                        <h3 className="text-xl font-bold">ƏDV Bölgüsü</h3>
                        <p className="text-slate-400 text-sm mt-1">Rate üzrə vergi daxilolmaları</p>
                    </div>

                    <div className="space-y-6">
                        <div className="flex justify-between items-end border-b border-slate-800 pb-4">
                            <div>
                                <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">18% Rate</span>
                                <p className="text-2xl font-black mt-1">{taxData.vat.by_rate.rate_18.toLocaleString()} <span className="text-sm font-bold opacity-50">AZN</span></p>
                            </div>
                            <div className="w-12 h-12 rounded-xl bg-blue-500/20 flex items-center justify-center text-blue-400">
                                <Percent size={20} />
                            </div>
                        </div>

                        <div className="flex justify-between items-end border-b border-slate-800 pb-4">
                            <div>
                                <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">0% Rate (Azad)</span>
                                <p className="text-2xl font-black mt-1">{taxData.vat.by_rate.rate_0.toLocaleString()} <span className="text-sm font-bold opacity-50">AZN</span></p>
                            </div>
                            <div className="w-12 h-12 rounded-xl bg-slate-800 flex items-center justify-center text-slate-500">
                                <Percent size={20} />
                            </div>
                        </div>

                        <div className="pt-4">
                            <div className="flex justify-between items-center mb-2">
                                <span className="text-sm font-bold text-slate-400">Yekun Ödənilməli ƏDV</span>
                                <span className="text-xl font-bold text-blue-400">{taxData.vat.total.toLocaleString()} AZN</span>
                            </div>
                            <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
                                <div className="bg-blue-500 h-full w-[100%]" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* 3. QUARTERLY & INCOME TAX */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Quarterly table */}
                <div className="bg-white p-8 rounded-3xl border shadow-sm space-y-6">
                    <div>
                        <h3 className="text-xl font-bold font-outfit">Rüblük Hesabatlar</h3>
                        <p className="text-sm text-slate-500">Hər rüb üzrə maliyyə və vergi xülasəsi</p>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full text-left border-collapse">
                            <thead>
                                <tr className="text-xs text-slate-400 uppercase tracking-widest border-b">
                                    <th className="pb-4 pt-2">Rüb</th>
                                    <th className="pb-4 pt-2">Gəlir</th>
                                    <th className="pb-4 pt-2">Xərc</th>
                                    <th className="pb-4 pt-2">ƏDV</th>
                                    <th className="pb-4 pt-2 text-right">Mənfəət</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-50">
                                {taxData.quarterly.map((q, idx) => (
                                    <tr key={idx} className="group hover:bg-slate-50/50 transition-colors">
                                        <td className="py-4 font-black text-slate-900">{q.name}</td>
                                        <td className="py-4 font-bold text-slate-700">{q.revenue.toLocaleString()}</td>
                                        <td className="py-4 text-slate-500">{q.expenses.toLocaleString()}</td>
                                        <td className="py-4 text-slate-500">{q.vat.toLocaleString()}</td>
                                        <td className={`py-4 font-black text-right ${q.profit >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                                            {q.profit.toLocaleString()}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>

                {/* Tax Estimates */}
                <div className="bg-white p-8 rounded-3xl border shadow-sm space-y-6">
                    <div className="flex justify-between items-center">
                        <div>
                            <h3 className="text-xl font-bold font-outfit">Təxmini Vergilər</h3>
                            <p className="text-sm text-slate-500">Müxtəlif vergi modelləri üzrə proqnozlar</p>
                        </div>
                        <div className="flex bg-slate-100 p-1 rounded-xl">
                            <button
                                onClick={() => setTaxMode('simplified')}
                                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${taxMode === 'simplified' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500'}`}
                            >
                                Sadə
                            </button>
                            <button
                                onClick={() => setTaxMode('profit')}
                                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${taxMode === 'profit' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500'}`}
                            >
                                Mənfəət
                            </button>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 gap-4">
                        {taxMode === 'simplified' ? (
                            <div className="bg-blue-50 border border-blue-100 p-6 rounded-2xl space-y-4">
                                <div className="flex justify-between items-center">
                                    <span className="text-sm font-bold text-blue-900">Sadələşdirilmiş Vergi (2%)</span>
                                    <span className="text-2xl font-black text-blue-600">{taxData.income_tax.estimates.simplified_2pct.toLocaleString()} AZN</span>
                                </div>
                                <p className="text-xs text-blue-700 opacity-70">Ümumi dövriyyə (Gəlir) əsasında hesablanır.</p>
                            </div>
                        ) : (
                            <div className="space-y-4">
                                <div className="bg-indigo-50 border border-indigo-100 p-6 rounded-2xl space-y-4">
                                    <div className="flex justify-between items-center">
                                        <span className="text-sm font-bold text-indigo-900">Mənfəət Vergisi (20%)</span>
                                        <span className="text-2xl font-black text-indigo-600">{taxData.income_tax.estimates.profit_20pct.toLocaleString()} AZN</span>
                                    </div>
                                    <p className="text-xs text-indigo-700 opacity-70">Gəlir ilə xərc fərqi əsasında standart dərəcə ilə hesablanır.</p>
                                </div>
                                <div className="bg-green-50 border border-green-100 p-6 rounded-2xl space-y-4">
                                    <div className="flex justify-between items-center">
                                        <span className="text-sm font-bold text-green-900">Mikro Sahibkar (5%)</span>
                                        <span className="text-2xl font-black text-green-600">{taxData.income_tax.estimates.micro_5pct.toLocaleString()} AZN</span>
                                    </div>
                                    <p className="text-xs text-green-700 opacity-70">Gəlir və xərc fərqi əsasında 75% güzəştli dərəcə ilə.</p>
                                </div>
                            </div>
                        )}
                    </div>

                    <div className="pt-2">
                        <div className="bg-gray-50 rounded-2xl p-4 flex items-start gap-3">
                            <div className="p-2 bg-white rounded-lg border text-slate-400">
                                <FileText size={16} />
                            </div>
                            <p className="text-[10px] text-slate-500 leading-relaxed italic">
                                * Bu rəqəmlər yalnız məlumatlandırma məqsədi daşıyır və tətbiqdə olan dataya əsaslanır.
                                Rəsmi bəyannamələr üçün peşəkar mühasibat xidmətindən istifadə etməyiniz tövsiyə olunur.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Print Only Summary Table */}
            <div className="hidden print:block mt-12">
                <h3 className="text-xl font-bold mb-6">İl Sonu Maliyyə Xülasəsi</h3>
                <div className="grid grid-cols-2 gap-12">
                    <div className="space-y-4">
                        <div className="flex justify-between border-b py-2"><span>Yekun Gəlir:</span><span className="font-bold">{taxData.income_tax.revenue.toLocaleString()} AZN</span></div>
                        <div className="flex justify-between border-b py-2"><span>Yekun Xərc:</span><span className="font-bold">{taxData.income_tax.expenses.toLocaleString()} AZN</span></div>
                        <div className="flex justify-between border-b py-2 text-xl font-black pt-4"><span>Xalis Mənfəət:</span><span>{taxData.income_tax.tax_base.toLocaleString()} AZN</span></div>
                    </div>
                    <div className="space-y-4">
                        <div className="flex justify-between border-b py-2"><span>Hesablanmış ƏDV (Yekun):</span><span className="font-bold">{taxData.vat.total.toLocaleString()} AZN</span></div>
                        <div className="flex justify-between border-b py-2"><span>Müştəri Sayı:</span><span className="font-bold">{taxData.summary.customer_count}</span></div>
                        <div className="flex justify-between border-b py-2"><span>Ən Uğurlu Ay:</span><span className="font-bold">{taxData.summary.best_month}</span></div>
                    </div>
                </div>
                <div className="mt-20 border-t pt-8 text-center text-xs text-slate-400">
                    Sənəd InvoiceAZ platforması tərəfindən {new Date().toLocaleString('az-AZ')} tarixində generasiya edilmişdir.
                </div>
            </div>
        </div>
    );
};

export default TaxReports;
