# Generated by Django 5.2.11 on 2026-02-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_expense_client_expense_currency_expense_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('office', 'Ofis ləvazimatları'), ('salary', 'Maaşlar'), ('marketing', 'Marketinq'), ('rent', 'İcarə və Kommunal'), ('travel', 'Ezamiyyət'), ('software', 'Proqram və Abunəliklər'), ('transport', 'Nəqliyyat və Yanacaq'), ('hardware', 'Avadanlıq və Texnika'), ('tax', 'Vergi və Dövlət rüsumları'), ('bank', 'Bank və Komissiya'), ('training', 'Təlim və Tədris'), ('other', 'Digər')], default='other', max_length=20),
        ),
    ]
