# Generated by Django 5.2.11 on 2026-02-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_theme',
            field=models.CharField(choices=[('modern', 'Müasir'), ('classic', 'Klassik'), ('minimal', 'Minimal')], default='modern', max_length=20),
        ),
    ]
