# Generated by Django 5.2.11 on 2026-02-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoiceitem_deleted_at_invoiceitem_is_deleted_and_more'),
        ('users', '0015_alter_teammember_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('business', 'invoice_number')},
        ),
    ]
