# Generated by Django 5.2.11 on 2026-02-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_tax_deductible',
            field=models.BooleanField(default=True, help_text='Bu xərc vergi bəyannaməsində gəlirdən çıxılsınmı?'),
        ),
    ]
