# Generated by Django 5.2.11 on 2026-02-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_expense_is_tax_deductible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('RUB', 'RUB'), ('GBP', 'GBP')], default='AZN', max_length=3),
        ),
    ]
