# Generated by Django 5.2.11 on 2026-03-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_invoice_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
    ]
