# Generated by Django 5.2.11 on 2026-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('free', 'Pulsuz'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
