# Generated by Django 5.2.11 on 2026-02-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_2fa_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
        ),
    ]
