# Generated by Django 5.2.11 on 2026-02-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_business_budget_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/'),
        ),
    ]
