# Generated by Django 5.2.11 on 2026-02-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_business_logo_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Slug name (e.g., 'free', 'pro')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Display name (e.g., 'Pulsuz', 'Pro')", max_length=100)),
                ('invoices_per_month', models.IntegerField(blank=True, default=5, null=True)),
                ('clients_limit', models.IntegerField(blank=True, default=10, null=True)),
                ('expenses_per_month', models.IntegerField(blank=True, default=20, null=True)),
                ('businesses_limit', models.IntegerField(blank=True, default=1, null=True)),
                ('has_forecast_analytics', models.BooleanField(default=False)),
                ('has_csv_export', models.BooleanField(default=False)),
                ('has_premium_pdf', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('team_members_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('has_custom_themes', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.subscriptionplan'),
        ),
    ]
