# Generated by Django 5.2.11 on 2026-02-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscriptionplan_user_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_invoice_theme',
            field=models.CharField(default='modern', max_length=20),
        ),
    ]
