# Generated by Django 5.2.11 on 2026-02-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Menecer'), ('ACCOUNTANT', 'Mühasib'), ('INVENTORY_MANAGER', 'Anbar Meneceri'), ('SALES_REP', 'Satış Təmsilçisi')], default='SALES_REP', max_length=20),
        ),
    ]
