# Generated by Django 5.2.11 on 2026-02-22 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_referral_fields_discountcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('MANAGER', 'Menecer'), ('ACCOUNTANT', 'Mühasib'), ('INVENTORY_MANAGER', 'Anbar Meneceri'), ('SALES_REP', 'Satış Təmsilçisi')], default='SALES_REP', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'inviter')},
            },
        ),
    ]
