# Generated by Django 5.2.11 on 2026-02-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_teammemberinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly sales target for Sales Rep', max_digits=12),
        ),
    ]
