# Generated by Django 5.2.11 on 2026-02-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_teammember_monthly_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='products_limit',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
