# Generated by Django 5.2.11 on 2026-02-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_subscriptionplan_products_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_white_label',
            field=models.BooleanField(default=False, help_text="Whether to hide 'Powered by InvoiceAZ' branding"),
        ),
    ]
