# Generated by Django 5.2.11 on 2026-02-24 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_subscriptionplan_has_white_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teammemberinvitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teammember',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='users.business'),
        ),
        migrations.AddField(
            model_name='teammemberinvitation',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.business'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('business', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='teammemberinvitation',
            unique_together={('email', 'business')},
        ),
    ]
