# Generated by Django 5.2.11 on 2026-02-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_teammember_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_currency',
            field=models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('RUB', 'RUB'), ('GBP', 'GBP')], default='AZN', max_length=3),
        ),
    ]
