# Generated by Django 5.2.11 on 2026-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_subscriptionplan_price_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
