# Generated by Django 5.2.11 on 2026-03-07 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_cancel_at_period_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('too_expensive', 'Bahadır'), ('missing_features', 'Lazımi özəllik yoxdur'), ('hard_to_use', 'İstifadəsi çətindir'), ('switching_to_competitor', 'Başqa xidmətə keçirəm'), ('no_longer_needed', 'Artıq ehtiyac yoxdur'), ('other', 'Digər')], max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_reasons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
