# Generated by Django 5.2.11 on 2026-03-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_cancellationreason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['sort_order', 'price_monthly'], 'verbose_name': 'Abunəlik Planı', 'verbose_name_plural': 'Abunəlik Planları'},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Plan haqqında qısa açıqlama'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_activity_log',
            field=models.BooleanField(default=False, help_text='Fəaliyyət jurnalı (audit trail)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_bulk_operations',
            field=models.BooleanField(default=False, help_text='Toplu əməliyyatlar (müştəri təyinatı və s.)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_client_ratings',
            field=models.BooleanField(default=False, help_text='Müştəri ödəniş reytinqi (A, B, C, D)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_duplicate_invoice',
            field=models.BooleanField(default=True, help_text='Faktura dublikat etmə'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_email_sending',
            field=models.BooleanField(default=False, help_text='Fakturanı e-poçtla göndərmə'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_etag_xml',
            field=models.BooleanField(default=False, help_text='E-qaime XML yaratma (e-vergi)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_multi_currency',
            field=models.BooleanField(default=False, help_text='Çoxvalyutalı dəstək (USD, EUR, TRY, RUB, GBP)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_overdue_reminders',
            field=models.BooleanField(default=False, help_text='Vaxtı keçmiş fakturalar üçün avtomatik xatırlatma'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_payment_analytics',
            field=models.BooleanField(default=False, help_text='Ödəniş analitikası (heatmap, sürət, metod)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_public_sharing',
            field=models.BooleanField(default=True, help_text='Fakturanı ictimai link ilə paylaşma'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_stock_alerts',
            field=models.BooleanField(default=False, help_text='Aşağı stok xəbərdarlıqları'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_tax_reports',
            field=models.BooleanField(default=False, help_text='Vergi hesabatları'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_team_gps',
            field=models.BooleanField(default=False, help_text='Komanda üzvü GPS lokasiya izləmə'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_vip_support',
            field=models.BooleanField(default=False, help_text='VIP / Prioritet dəstək'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Plan aktiv/deaktiv'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='purchase_orders_per_month',
            field=models.IntegerField(blank=True, default=0, help_text='Aylıq satınalma sifarişi limiti (boş = limitsiz)', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Sıralama ardıcıllığı (kiçik=əvvəl)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='storage_limit_mb',
            field=models.IntegerField(blank=True, default=50, help_text='Yaddaş limiti MB (boş = limitsiz)', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='warehouses_limit',
            field=models.IntegerField(blank=True, default=1, help_text='Anbar limiti (boş = limitsiz)', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='businesses_limit',
            field=models.IntegerField(blank=True, default=1, help_text='Biznes profili limiti (boş = limitsiz)', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='clients_limit',
            field=models.IntegerField(blank=True, default=10, help_text='Müştəri limiti (boş = limitsiz)', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='expenses_per_month',
            field=models.IntegerField(blank=True, default=20, help_text='Aylıq xərc limiti (boş = limitsiz)', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_api_access',
            field=models.BooleanField(default=False, help_text='REST API girişi (xarici inteqrasiya)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_csv_export',
            field=models.BooleanField(default=False, help_text='CSV/Excel eksport'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_custom_themes',
            field=models.BooleanField(default=False, help_text='Özəl faktura temaları'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_forecast_analytics',
            field=models.BooleanField(default=False, help_text='Proqnoz analitikası (gəlir, cash flow)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_premium_pdf',
            field=models.BooleanField(default=False, help_text='Premium PDF dizaynları (Modern, Classic, Minimal)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_white_label',
            field=models.BooleanField(default=False, help_text="'Powered by InvoiceAZ' brendinqini gizlət"),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='invoices_per_month',
            field=models.IntegerField(blank=True, default=5, help_text='Aylıq faktura limiti (boş = limitsiz)', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='label',
            field=models.CharField(help_text="Göstərilən ad (məs: 'Pulsuz', 'Pro', 'Premium')", max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text="Slug adı (məs: 'free', 'pro', 'premium')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Aylıq qiymət (AZN)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_yearly',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='İllik qiymət (AZN)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='products_limit',
            field=models.IntegerField(blank=True, default=20, help_text='Məhsul limiti (boş = limitsiz)', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='team_members_limit',
            field=models.IntegerField(blank=True, default=0, help_text='Komanda üzvü limiti (boş = limitsiz)', null=True),
        ),
    ]
